runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /models
  static_dir: models

- url: /templates
  static_dir: templates

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
